@startuml
title クラス図

class クラス名 {
  + フィールド1 
  - フィールド2
  # メソッド1(引数1: 型, 引数2: 型): 戻り値型
  ~ メソッド2()
}

class 社員 {
  社員番号: string
  勤怠を入力する()
}

class エンジニア extends 社員 {
  プログラミング()
}

class デザイナー extends 社員 {
  デザイン()
}

@enduml

/*

フィールド: '可視性 フィールド名: 型'
メソッド: '可視性 メソッド名(引数名: 引数型): 戻り値型'

可視性
+ パブリック
- プライベート
# プロテクテッド
~ パッケージプライベート
*/